### PR TITLE
Remove unneccessary attr_readers

### PR DESCRIPTION
**Pull request by sobbybutter**
It looks like the attr_readers aren't necessary for the given module.

### CODE REVIEW

**Comment by set5think** [comment]
Hi @sobbybutter - can you rebase this and push again?  The build will succeed when this branch has the latest changes in master.  Thanks.

**Comment by sobbybutter** [comment]
Hi @set5think. Just a heads up - new to git and this is my first push to an open source project. Here's what I did:
1) rebased upstream/master onto my cleanup branch
2) git push -f'd the branch to my forked fastly-rails repo

Is this the proper way to do it? Is the forced push necessary? Thanks!

**Comment by set5think** [comment]
@sobbybutter - yep you did it properly.  The force push is necessary because during the rebase process, you changed the history of your git branch, so the remote git branch and the local git branch were out of sync, and the `force` overwrites the remote's history to whatever you are telling it to be.

**Comment by sobbybutter** [comment]
@set5think thanks!

**Pull request merged**
